version: '3'
services:
  php:
    build: ./image/fpm
    links: 
      - "db: db"
    volumes:
      - ../site/:/var/www/html
  nginx:
    build: ./image/fpm
    container_name: test_nginx
    image: nginx:alpine
    links:
      - "php: fpm"
    ports:
      - 8080:80
    volumes:
      - ../site/:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
      image: mariadb:latest
      container_name: db
      restart: always
      environment:
        MYSQL_USER: admin
        MYSQL_PASSWORD: 12345
        MYSQL_ROOT_PASSWORD: 12345
        MYSQL_DATABASE: testdk